StockControl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/base.html'), name='index'),
    path('', include('compra.urls')),
]

compra/urls.py
from django.urls import path
from . import views

app_name = 'compra'

urlpatterns = [
    path('productos/', views.lista_productos, name='lista_productos'),  # URL para listar productos
    path('agregar-producto/', views.agregar_producto, name='agregar_producto'),  # URL para agregar producto
    path('agregar-proveedores/', views.agregar_proveedor, name='agregar_proveedor'),  # URL para agregar proveedor
    path('proveedores/', views.lista_proveedores, name='lista_proveedores'),  # URL para listar proveedores
    ]

compra/models.py
from django.db import models

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    dni = models.CharField(max_length=10)

    class Meta:
        verbose_name_plural = "proveedores"

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock_actual = models.IntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

compra/forms.py
from django import forms
from .models import Proveedor, Producto

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['nombre', 'apellido', 'dni']

    def clean_dni(self):
        dni = self.cleaned_data['dni']
        if not dni.isdigit():
            raise forms.ValidationError("El DNI debe ser un número.")
        return dni

"""class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'precio', 'stock_actual', 'proveedor']"""

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'precio', 'stock_actual', 'proveedor']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Filtrar los proveedores disponibles en el campo desplegable
        self.fields['proveedor'].queryset = Proveedor.objects.all()


    def clean_precio(self):
        precio = self.cleaned_data['precio']
        if precio <= 0:
            raise forms.ValidationError("El precio debe ser mayor que cero.")
        return precio

compra/views.py
from django.shortcuts import render, redirect
from .models import Producto, Proveedor
from .forms import ProductoForm, ProveedorForm

def lista_productos(request):
    productos = Producto.objects.all()
    return render(request, 'compra/lista_productos.html', {'productos': productos})


def agregar_producto(request):
    proveedores = Proveedor.objects.all()
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('compra:lista_productos')

    else:
        form = ProductoForm()
    return render(request, 'compra/agregar_producto.html', {'form': form, 'proveedores': proveedores})

def lista_proveedores(request):
    proveedores = Proveedor.objects.all() # Obtener todos los proveedores de la base de datos
    # Renderizar la plantilla lista_proveedores.html con los proveedores
    return render(request, 'compra/lista_proveedores.html', {'proveedores': proveedores})


def agregar_proveedor(request):
    if request.method == 'POST':
        form = ProveedorForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirigir a la lista de proveedores después de guardar correctamente
            return redirect('compra:lista_proveedores')
    else:
        form = ProveedorForm()
    return render(request, 'compra/agregar_proveedor.html', {'form': form})

compra/templates/compra/agregar_producto.html
{% extends 'base/base.html' %}

{% block title %}Lista de Proveedores{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Agregar Nuevo Producto</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_producto">Nombre:</label>
                <input type="text" class="form-control" id="id_producto" placeholder="Ingrese un producto" name="nombre">
            </div>
            <div class="form-group">
                <label for="id_precio">Precio:</label>
                <input type="number" class="form-control" id="id_precio" placeholder="$" name="precio">
            </div>
            <div class="form-group">
                <label for="id_stock">Stock Actual:</label>
                <input type="number" class="form-control" id="id_stock" name="stock_actual">
            </div>
            <div class="form-group">
                <label for="id_proveedor">Proveedor:</label>
                <select class="form-control" id="id_proveedor" name="proveedor" name="proveedor">
                    {% for proveedor in proveedores %}
                        <option value="{{ proveedor.id }}">{{ proveedor.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Guardar Producto</button>
        </form>
        <hr class="my-4">
        <a href="{% url 'compra:lista_productos' %}" class="btn btn-link">Ver Lista de Productos</a>
    </div>
</body>
</html>

{% endblock %}

compra/templates/compra/agregar_proveedor.html
{% extends 'base/base.html' %}

{% block title %}Lista de Proveedores{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Agregar Nuevo Proveedor</h2>
        <form method="post" >
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre:</label>
                <input type="text" class="form-control" id="id_nombre" name="nombre">
            </div>
            <div class="form-group">
                <label for="id_apellido">Apellido:</label>
                <input type="text" class="form-control" id="id_apellido" name="apellido">
            </div>
            <div class="form-group">
                <label for="id_dni">DNI:</label>
                <input type="number"  pattern="\d{1,9}" class="form-control" id="id_dni" name="dni">
            </div>


            <button type="submit" class="btn btn-primary">Guardar Proveedor</button>
        </form>

        <a href="{% url 'compra:lista_proveedores' %}" class="btn btn-link">Ver Lista de Proveedores</a>

    </div>
    <script>
        // Obtener el campo de entrada del DNI
        var dniInput = document.getElementById('id_dni');

        // Agregar un evento de escucha para el evento 'input'
        dniInput.addEventListener('input', function() {
            // Si la longitud del valor del campo de entrada es mayor que 8
            if (this.value.length > 8) {
                // Establecer el valor del campo de entrada al substring de los primeros 8 caracteres
                this.value = this.value.substring(0, 8);
            }
        });
    </script>}
</body>
</html>

{% endblock %}

compra/templates/compra/lista_productos.html
{% extends 'base/base.html' %}

{% block title %}Lista de Proveedores{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Lista de Productos</h2>
        <a href="{% url 'compra:agregar_producto' %}" class="btn btn-link">Agregar nuevo Producto</a>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Stock Actual</th>
                    <th>Proveedor</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.id }}</td>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.precio }}</td>
                    <td>{{ producto.stock_actual }}</td>
                    <td>{{ producto.proveedor }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

compra/templates/compra/lista_proveedores.html
{% extends 'base/base.html' %}

{% block title %}Lista de Proveedores{% endblock %}

{% block content %}
<div class="container">
    <h2>Lista de Proveedores</h2>
    <a href="{% url 'compra:agregar_proveedor' %}" class="btn btn-link">Agregar nuevo proveedor</a>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>DNI</th>
            </tr>
        </thead>
        <tbody>
            {% for proveedor in proveedores %}
            <tr>
                <td>{{ proveedor.id }}</td>
                <td>{{ proveedor.nombre }}</td>
                <td>{{ proveedor.apellido }}</td>
                <td>{{ proveedor.dni }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inmobiliaria Salta</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <img src="{% static 'imagenes/saltainmueble.png' %}" width="100" height="100">
            <h1 class="custom-heading">Salta Inmuebles</h1>
            <p>Bienvenido a Salta Inmuebles. Encuentra tu hogar perfecto con nosotros.</p>
        </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                            <a class="nav-link"  href="{% url 'index' %}">Inicio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'compra:agregar_producto' %}">Agregar Producto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'compra:agregar_proveedor' %}">Agregar Proveedor</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'compra:lista_productos' %}">Lista de Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'compra:lista_proveedores' %}">Lista de Proveedores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="main-content">
    {% block content %}
    {% endblock %}
    </div>

    <footer>
        <div class="container text-center">
            <span class="text-muted">© 2024 Salta Inmuebles. Todos los derechos reservados.</span>
        </div>
    </footer>
</body>
</html>